endpoints = {
    "/documentation": ["NO-AUTHORIZATION-NEEDED"],
    "/swagger-ui": ["NO-AUTHORIZATION-NEEDED"],
    "/swagger-ui/index.html": ["NO-AUTHORIZATION-NEEDED"],
    "/alive": ["NO-AUTHORIZATION-NEEDED"],
    "/o8o4m3/elements-v1.csv": ["NO-AUTHORIZATION-NEEDED"],
    "/userguide.pdf": ["NO-AUTHORIZATION-NEEDED"],
    "/applicable-for": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/asset/fass-educational-material/": ["NO-AUTHORIZATION-NEEDED"],
    "/asset/medical-device/": ["NO-AUTHORIZATION-NEEDED"],
    "/asset/solid-dosage-form/marking/": ["NO-AUTHORIZATION-NEEDED"],
    "/asset/solid-dosage-form/photo/": ["NO-AUTHORIZATION-NEEDED"],
    "/aasset/substance/": ["NO-AUTHORIZATION-NEEDED"],
    "/asset/fass-supportive-material/": ["NO-AUTHORIZATION-NEEDED"],
    "/atc": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/atc/": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/atc/top-level": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/cities": ["FULL-ACCESS"],
    "/counties": ["FULL-ACCESS"],
    "/dhpc/": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/dhpc/all": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/dhpc/changelog": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/fass-educational-material/": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/fass-educational-material/all": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/fass-educational-material/changelog": [
        "FULL-ACCESS",
        "HUMAN-FASS-API",
        "VET-FASS-API",
    ],
    "/fass-educational-material": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/fass-environmental-information/": [
        "FULL-ACCESS",
        "HUMAN-FASS-API",
        "VET-FASS-API",
    ],
    "/fass-environmental-information/changelog": [
        "FULL-ACCESS",
        "HUMAN-FASS-API",
        "VET-FASS-API",
    ],
    "/fass-environmental-information": [
        "FULL-ACCESS",
        "HUMAN-FASS-API",
        "VET-FASS-API",
    ],
    "/fass-environmental-information-ready-for-review/": ["FULL-ACCESS", "IVL"],
    "/fass-environmental-information/all": [
        "FULL-ACCESS",
        "HUMAN-FASS-API",
        "VET-FASS-API",
    ],
    "/fass-environmental-information-ready-for-review/changelog": [
        "FULL-ACCESS",
        "IVL",
    ],
    "/fass-document/": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/fass-document/all": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/fass-document/changelog": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/medical-device": ["FULL-ACCESS", "SOLID-DOSAGE-FORM"],
    "/medical-device/": ["FULL-ACCESS", "SOLID-DOSAGE-FORM"],
    "/medical-device/all": ["FULL-ACCESS", "SOLID-DOSAGE-FORM"],
    "/medical-device/changelog": ["FULL-ACCESS", "SOLID-DOSAGE-FORM"],
    "/interchangeable-medicinal-products": [
        "FULL-ACCESS",
        "HUMAN-FASS-API",
        "VET-FASS-API",
    ],
    "/medicinal-product": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/medicinal-product/": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/medicinal-product/all": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/medicinal-product/ingredients/all": [
        "FULL-ACCESS",
        "HUMAN-FASS-API",
        "VET-FASS-API",
    ],
    "/medicinal-product/changelog": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/medicinal-product/search": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/organization": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/organization/": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/organization/all": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/organization/changelog": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/package": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/package/": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/package/all": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/medicine-shortage/all": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/medicine-shortage/changelog": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/medicine-shortage": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/medicine-shortage/": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/medicine-shortage/advice": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/medicine-shortage/url": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/medicine-shortage/advice/": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/fass-package-leaflet/": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/fass-package-leaflet/all": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/fass-package-leaflet/changelog": [
        "FULL-ACCESS",
        "HUMAN-FASS-API",
        "VET-FASS-API",
    ],
    "/online-pharmacy": ["FULL-ACCESS"],
    "/pharmacy": ["FULL-ACCESS"],
    "/pharmacies": ["FULL-ACCESS"],
    "/fass-safety-data-sheet/all": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/fass-safety-data-sheet/changelog": [
        "FULL-ACCESS",
        "HUMAN-FASS-API",
        "VET-FASS-API",
    ],
    "/fass-safety-data-sheet/": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/fass-smpc/all": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/fass-smpc/": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/fass-smpc/changelog": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/solid-dosage-form/medication-management/": ["FULL-ACCESS", "SOLID-DOSAGE-FORM"],
    "/solid-dosage-form/medication-management/all": [
        "FULL-ACCESS",
        "SOLID-DOSAGE-FORM",
    ],
    "/solid-dosage-form/medication-management/changelog": [
        "FULL-ACCESS",
        "SOLID-DOSAGE-FORM",
    ],
    "/solid-dosage-form/medication-management": ["FULL-ACCESS", "SOLID-DOSAGE-FORM"],
    "/solid-dosage-form/photo-identification/": ["FULL-ACCESS", "SOLID-DOSAGE-FORM"],
    "/solid-dosage-form/photo-identification/all": ["FULL-ACCESS", "SOLID-DOSAGE-FORM"],
    "/solid-dosage-form/photo-identification/changelog": [
        "FULL-ACCESS",
        "SOLID-DOSAGE-FORM",
    ],
    "/solid-dosage-form/photo-identification": ["FULL-ACCESS", "SOLID-DOSAGE-FORM"],
    "/pharmacy/stock/": ["FULL-ACCESS"],
    "/substance/": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/substance/all": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/substance/changelog": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/substance": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/fass-supportive-material/": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/fass-supportive-material/all": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/fass-supportive-material/changelog": [
        "FULL-ACCESS",
        "HUMAN-FASS-API",
        "VET-FASS-API",
    ],
    "/fass-supportive-material": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/glossary/all": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/vab/interchangeable": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/vab/medicinal-product": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/fab/organization/": ["FULL-ACCESS"],
    "/fab/package/barcode/": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/fab/product/": ["FULL-ACCESS"],
    "/custom/ehm/indication/": ["FULL-ACCESS", "E-HEALTH-AGENCY"],
    "/vet/package/barcode/": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/vet/medicinal-product": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/vet/species/all": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
    "/vet/species/atc/": ["FULL-ACCESS", "HUMAN-FASS-API", "VET-FASS-API"],
}
